trigger:
  branches:
    include:
      - dev

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'

  - script: |
      npm version patch
    displayName: 'Bump version'

  - task: Npm@1
    displayName: 'npm publish'
    inputs:
      command: publish
      verbose: false
      publishRegistry: useFeed
      publishFeed: '2f357eec-7fbb-4d00-a381-868738c3e9d5/8c5c80bb-b669-4f4e-b4bb-306394a4c68b'
